<?php

namespace mod_kom_peerla;

require_once realpath(__DIR__).'/BasicDataPoint2D.php';

/**
 * A data point objects, which can be used to calculate the sum of 
 * multiple values.
 *
 * @author Christoph Bohr
 */
class SumCalculationDataPoint2D extends BasicDataPoint2D {
	
	protected $xSum = 0;
	protected $ySum = 0;
	
	protected $xIsNominal = false;
	protected $yIsNominal = false;
	
	/**
	 * Add an additional x value.
	 * 
	 * getValueX will return the sum of all values added via this
	 * method. 
	 * 
	 * @param int|float $value  
	 */
	function addValueX($value){
		if (is_numeric($value) && !$this->xValueIsNominal()){
			$this->xSum += $value;
		}
	}
	
	/**
	 * Add an additional y value.
	 * 
	 * getValueY will return the sum of all values added via this
	 * method. 
	 * 
	 * @param int|float $value  
	 */
	function addValueY($value){
		if (is_numeric($value) && !$this->yValueIsNominal()){
			$this->ySum += $value;
		}
	}
	
	/**
	 * Set the x coordinate value.
	 * 
	 * Calling this method will overwrite the values generated by addValueX.
	 * 
	 * @param mixed $value
	 */
	public function setValueX($value) {
		$this->xSum = $value;
	}

	/**
	 * Set the y coordinate value.
	 * 
	 * Calling this method will overwrite the values generated by addValueY.
	 * 
	 * @param mixed $value
	 */
	public function setValueY($value) {
		$this->ySum = $value;
	}
	
	/**
	 * Set if the x coordinate value is a nominal value.
	 * 
	 * If false is given, a ordinal value is expected.
	 * 
	 * @param bool $nominal
	 */
	public function setXvalueIsNominal($nominal=true){
		$this->xIsNominal = $nominal;
	}
	
	/**
	 * Set if the y coordinate value is a nominal value.
	 * 
	 * If false is given, a ordinal value is expected.
	 * 
	 * @param bool $nominal
	 */
	public function setYvalueIsNominal($nominal=true){
		$this->yIsNominal = $nominal;
	}

	public function getValueX() {
		return $this->xSum;
	}

	public function getValueY() {
		return $this->ySum;
	}

	public function xValueIsNominal() {
		return $this->xIsNominal;
	}

	public function yValueIsNominal() {
		return $this->yIsNominal;
	}
	
}
